### ISSUE TITLE
Love your videos

### ISSUE THREAD

**Issue by 6nz** [sfx2me/simple-auth-system#2]
if u dont know how to code why u even doing it lmfao

**Comment by ShireDev** [comment]
Hello 👋 If you have a recommandation you can make a PR!
(This repository if for beginner developer!)

**Comment by 6nz** [comment]
> Hello 👋 If you have a recommandation you can make a PR!
> (This repository is for beginner developer!)

He is a skid.

**Comment by 6nz** [comment]
> Hello 👋 If you have a recommandation you can make a PR!
> (This repository is for beginner developer!)

Maybe this repo is for you. This repo is pointless and easy to crack

**Comment by 6nz** [comment]
Look at his "advanced auth System" he copy pasted the example from keyauth lmao

**Comment by ShireDev** [comment]
> Look at his "advanced auth System" he copy pasted the example from keyauth lmao

If you want to be dumb you have succeeded...
(You have forked the repo 😂

**Comment by 6nz** [comment]
> > Look at his "advanced auth System" he copy pasted the example from keyauth lmao
> 
> If you want to be dumb you have succeeded... (You have forked the repo 😂)

bro are u dumb? LOOOL

**Comment by 6nz** [comment]
> > Look at his "advanced auth System" he copy pasted the example from keyauth lmao
> 
> If you want to be dumb you have succeeded... (You have forked the repo 😂)

I forked to make a pull req

**Comment by ShireDev** [comment]
> im part of the keyauth support team

Oh the support team of keyauth are really annoying!

**Comment by 6nz** [comment]
why u switching topics?

**Comment by 6nz** [comment]
> > Look at his "advanced auth System" he copy pasted the example from keyauth lmao
> 
> If you want to be dumb you have succeeded... (You have forked the repo 😂)

calling me dumb for making a pull req to fix something?

**Comment by 6nz** [comment]
lmao u have some serious problems

**Comment by 6nz** [comment]
also calling keyauth team annoying? what u probably not even in the server and u prolly dont know anything abt keyauth
